name: Deploy to Vercel

on:
  push:
    branches:
      - main
      - feat/ci

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: npx vercel --yes --token $VERCEL_TOKEN --project tech4r